[module/xworkspaces]
type = internal/xworkspaces

label-active = "󰝥"
label-active-foreground = ${colors.blue}
label-active-background = ${colors.background-alt}
label-active-padding = 2

label-occupied = "󰝥"
label-occupied-foreground = ${colors.primary}
label-occupied-background = ${colors.background-alt}
label-occupied-padding = 2

label-urgent = "󰝥"
label-urgent-foreground = ${colors.alert}
label-urgent-background = ${colors.background-alt}
label-urgent-padding = 2

label-empty = "󰝥"
label-empty-foreground = ${colors.disabled}
label-empty-background = ${colors.background-alt}
label-empty-padding = 2


[module/launcher]
type = custom/text
content = "SNUAILAB"
content-foreground = ${colors.blue}
click-left = rofi -show drun
content-padding = 3
content-font = 3

[module/powermenu]
type = custom/text
content = "   "
content-foreground = ${colors.alert}
click-left = exec /usr/bin/gnome-session-quit --power-off
content-padding = 0
content-font = 5

[module/date]
type = internal/date
interval = 1
date = %p %I:%M 
date-alt = %a, %B %d

; label = "%{A1:eww open-many --toggle background-closer main:}%date%%{A}"
; label-foreground = ${colors.foreground}


[module/pulseaudio]
type = internal/pulseaudio

; Use PA_VOLUME_UI_MAX (~153%) if true, or PA_VOLUME_NORM (100%) if false
; Default: true
use-ui-max = false

; Interval for volume increase/decrease (in percent points)
; Default: 5
interval = 5

; Available tags:
;   <label-volume> (default)
;   <ramp-volume>
;   <bar-volume>
format-volume = "%{A1:$HOME/.config/eww/System-Menu/launch:}<ramp-volume>%{A}"

; Available tags:
;   <label-muted> (default)
;   <ramp-volume>
;   <bar-volume>
format-muted = "%{A1:$HOME/.config/eww/System-Menu/launch:}<label-muted>%{A}"

; Available tokens:
;   %percentage% (default)
;   %decibels%
;label-volume = %percentage%%

; Available tokens:
;   %percentage% (default)
;   %decibels%
label-muted = "󰝟"
label-muted-foreground = ${colors.alert}
label-muted-background = ${colors.background-alt}
label-muted-font = 9
label-muted-padding = 1

; Only applies if <ramp-volume> is used
ramp-volume-0 = "󰕿"
ramp-volume-1 = "󰖀"
ramp-volume-2 = "󰖀"
ramp-volume-3 = "󰕾"
ramp-volume-4 = "󰕾"
ramp-volume-5 = "󰕾"
ramp-volume-font = 9
ramp-volume-background = ${colors.background-alt}
ramp-volume-padding = 1

; Right and Middle click
click-right = amixer sset Master toggle
click-middle = 

[module/github]
type = custom/script
exec = $HOME/.config/polybar/scripts/github
format = <label>
label = %output%
format-prefix = "󰊤 "
format-prefix-font = 3
interval = 60
format-padding = 3
click-left = google-chrome https://github.com

[module/seperator]
type = custom/text
content = "  "
content-font = 3

[module/previous]
type = custom/script
format-prefix-padding = 1
format-font = 5
format-background = ${colors.background-alt} 
format-foreground = ${colors.foreground}
exec = echo "  "
; line-size = 5
click-left = "spotifyctl -q previous"

[module/next]
type = custom/script
format-prefix-padding = 1
format-font = 5
format-background = ${colors.background-alt} 
format-foreground = ${colors.foreground}
exec = echo "  "
click-left = "spotifyctl -q next"

[module/playpause]
type = custom/script
format-prefix-padding = 1
format-font = 5
format-background = ${colors.background-alt} 
format-foreground = ${colors.foreground}
label-font = 0
exec = echo "  "
; hook-0 = echo "   "
; hook-1 = echo ""
; hook-2 = echo ""
; format-font = 5
initial = 1
line-size = 1
click-left = "spotifyctl -q playpause"

[module/spotify]
type = custom/script
tail = true
interval = 1
format-prefix = "%{A1:eww open-many --toggle background-closer player:} %{A}"
format-prefix-padding = 1
format-font = 5
label-font = 2
format-background = ${colors.background-alt} 
format-foreground = ${colors.foreground}
format = "%{A1:eww open-many --toggle background-closer player:}<label>%{A}"
; exec = ~/.config/polybar/scripts/scroll-spotify
exec = spotifyctl -q status --format '%artist%: %title%'

[module/bluetooth]
type = custom/script
exec = ~/.config/polybar/scripts/bluetooth
interval = 2
click-left = exec gnome-control-center --class=floating_window bluetooth
format-padding = 1
format-font = 2
format-background = ${colors.background-alt}
format-foreground = ${colors.foreground}

[module/microphone]
type = custom/script
exec = ~/.config/polybar/scripts/microphone
interval = 5
format-padding = 1
format-font = 14
format-background = ${colors.background-alt}
format-foreground = ${colors.foreground}

